name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          USERNAME: MaxChangInnodisk
          token: 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
          submodules: true

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Create zip
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-${{ steps.get_version.VERSION }}.zip ${{ github.event.repository.name }} -r
          
      - uses: pyTooling/Actions/releaser@r0
        with:
          USERNAME: MaxChangInnodisk
          token: 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
          tag: ${{ steps.get_version.VERSION }}
          files: ${{ github.event.repository.name }}-${{ steps.get_version.VERSION }}.zip
